### ISSUE TITLE
The warmup CT2MR pre-trained model.

### ISSUE THREAD

**Issue by dongdongtong** [TFboys-lzz/MPSCL#1]
Hello, Nice work. But I have a question about how to obtain the warmup model of CT2MR.

The pre-trained model could achieve ~54.1% Dice score on target test_mr. And when I loaded the warmup model and continued the warmup stage, I could obtain a ~63% Dice score on target test_mr, which was very close to your reported result of AdvEnt/AdaSeg in the MPSCL paper.

BUT, when I conducted the CT2MR warmup stage with the default config.yml from the scratch, I could only achieve ~30% Dice on target test_mr, which makes me very confused.

Could you please provide some advice? Very thanks.

**Comment by TFboys-lzz** [comment]
Thank you for your interest in our work! 

We upload the config.yml of the warmup stage (i.e., warmup_CT2MR.yml and warmup_MR2CT.yml). Plz check if the DeeplabV2 is initialized with pre-trained  parameter from ImageNet.
The pre-trained model can be downloaded from [https://drive.google.com/drive/folders/1UFqj18A4vuoknldoqAkg9tx7S6CUjxRL](url)

**Comment by dongdongtong** [comment]
Very thanks for your immediately reply, I will make a try then.

**Comment by dongdongtong** [comment]
After the segmentation model was initialized with the pre-trained parameters, everything worked!
