### ISSUE TITLE
shape error

### ISSUE THREAD

**Issue by iTomxy** [TFboys-lzz/MPSCL#11]
Hi, I'm pretraining the deeplabv2 to generate prototypes on another dataset. I find that the prediction is down-sampled to 33 $\times$ 33 but not up-sampled. Why is that? Did you also down-sample labels? But it seems that you did not down-sample labels before calculating BCE and dice loss in [train_UDA.py](https://github.com/TFboys-lzz/MPSCL/blob/main/domain_adaptation/train_UDA.py). 

Note that I notice that there is a `label_downsample` function in [train_UDA.py](https://github.com/TFboys-lzz/MPSCL/blob/main/domain_adaptation/train_UDA.py). But it is only used in the `update_class_center_iter` function, and that does not affect the shape of labels used for BCE and dice loss calculation.

Thanks.

**Comment by TFboys-lzz** [comment]
We have defined the interp function as: [https://github.com/TFboys-lzz/MPSCL/blob/bb58bde64e904f167cad9ed7b6f4f64d3977be1e/domain_adaptation/train_UDA.py#L189](url)

**Comment by TFboys-lzz** [comment]
we have defined the interp function as: https://github.com/TFboys-lzz/MPSCL/blob/bb58bde64e904f167cad9ed7b6f4f64d3977be1e/domain_adaptation/train_UDA.py#L189

**Comment by iTomxy** [comment]
Oh, my bad. Thanks. You're really responsive.
