### ISSUE TITLE
CLASS_CENTER_FEA_INIT

### ISSUE THREAD

**Issue by memeFish5** [TFboys-lzz/MPSCL#12]
您好，感谢您的工作和代码，请问一下初始prototype是如何获得的，是随机的吗还是从数据集中求得的

**Comment by TFboys-lzz** [comment]
我们首先利用源域数据对模型进行warmup预训练（大约4000个iteration），然后利用源域的类中心初始化原型，在后续的对抗训练过程中，通过动量更新的方式不断更新原型。

**Comment by memeFish5** [comment]
感谢您的回复，结合其他issue我了解了，非常喜欢您的这个工作
