### ISSUE TITLE
data processing

### ISSUE THREAD

**Issue by memeFish5** [TFboys-lzz/MPSCL#13]
Hello, Thanks for you code, I like you work.  

In domain_adaptation/eval_UDA.py line 68 :  
`img_mean   = np.array((104.00698793, 116.66876762, 122.67891434), dtype=np.float32)`  
if I want to test my own dataset,  I need to replace img_mean up to my dataset right?  
Is the value equal to the mean value of my test dataset?

**Comment by TFboys-lzz** [comment]
If you're testing on your own dataset, I don't think there's a need to change it, since the mean is the network we used to pre-train at ImageNet. However, I think the best way to do this might be for you to fine-tune it on your own dataset first.

**Comment by memeFish5** [comment]
Thanks, I‘ll try
