### ISSUE TITLE
How to initialize the category center

### ISSUE THREAD

**Issue by dongdongtong** [TFboys-lzz/MPSCL#3]
Hi, it's me again.

I want to try your code on another dataset, the abdominal dataset, which was reported in the SIFA[TMI] paper. But I cannot find the initialization code for calculating category centers. Could you plz release the corresponding code?

Thanks!

**Comment by TFboys-lzz** [comment]
Sorry I didn't see it until now.
For calculating category centers, you first need pretrain the model on the source dataset,
and then you can calculate the category center by https://github.com/TFboys-lzz/MPSCL/blob/bb58bde64e904f167cad9ed7b6f4f64d3977be1e/domain_adaptation/train_UDA.py#L101-L127

**Comment by dongdongtong** [comment]
Sovled. Thanks for your kindly reply.

**Comment by cqjtuhxf** [comment]
May I ask if you have solved it?
