### ISSUE TITLE
train on another dataset 

### ISSUE THREAD

**Issue by wh-isper** [TFboys-lzz/MPSCL#5]
Hi author! I have a doubt about using your code to train on another dataset. At first, I need to pre-train a segmentation model on the source domain to obtain the initial category prototypes. Is it necessary to pre-train main and aux discriminators?

**Comment by wh-isper** [comment]
Besides, in ct2mr.yml and mr2ct.yml, you choose different models for D_type(original_d and patchGAN), which one should i choose?

**Comment by TFboys-lzz** [comment]
Hi wh-isper:
    If you just want to get the initial category prototypes, the discriminators are not required to be pre-trained.
About the selection of the discriminator,  you can verify it on your own dataset. We found experimentally here that these two discriminators have their own advantages in two different directions

**Comment by wh-isper** [comment]
Thanks for your quick reply!
